Some typos, tweaks, and minor error corrections in ES translation
githubtraining/introduction-to-github pull request #55
Opened 2020-08-31 11:19 UTC by mberasategi

2020-09-07 14:44 UTC, brianamarie commented
Awesome, thank you for this, @mberasategi! 

![sparkley gif](https://media.giphy.com/media/5zvQm44QfVadjn3fiE/giphy.gif)

@davenowell @droidpl would you have bandwidth to review this PR?

2020-09-10 09:03 UTC, davenowell requested changes
@mberasategi - I have requested one change.  Thank you for your work!

2020-09-10 09:13 UTC, mberasategi commented on responses/es/04_commit-something.md
> +- Usa la voz activa. Por ejemplo, "añade" en vez de "añadí" y "une" en vez de "uní".
Agree. I didn't even consider this. Will change to:

> - Usa la voz activa. Por ejemplo, "Añade la funcionalidad xx" en vez de "Añadida la funcionalidad xx" y "Combina los cambios" en lugar de "Combinados los cambios".

2020-09-10 11:11 UTC, davenowell commented
> BTW @davenowell , here's where we have the `propuesta` (for issue) all over the place. It should be changed to `incidencia`, right? Will do as soon as you confirm!

@mberasategi  If you could refer to http://docs.github.com/es and use whichever word appears there, that would be fine. I think the word "propuesta" is used.

2020-09-10 13:54 UTC, mberasategi commented
Alright, Docs says "propuesta". I've went through [replacing all "propuesta"s with "incidencia" in Communicating using Markdown](https://github.com/githubtraining/communicating-using-markdown/pull/28#discussion_r483594142)... 🤦🏼  

I guess those should be replaced back then!

2020-09-21 09:39 UTC, merged